name: bash-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Run Bash
      run: |
       sudo apt-get install -y jq
       bash -n strava.sh
       bash -n token.sh